### ISSUE TITLE
laravel-doctrine/orm: 2.0 support

### ISSUE THREAD

**Issue by cesaric** [bolivir/laravel-doctrine-sanctum#62]
Can the composer.json requirement be changed to  **"laravel-doctrine/orm": "^1.0 || ^2.0"** which would then support **"doctrine/dbal":"3.0"** too?

**Comment by bolivir** [comment]
Should now be supported see https://github.com/bolivir/laravel-doctrine-sanctum/releases/tag/v2.0.0-rc.1

**Comment by cesaric** [comment]
v2.0.0-rc.1 is working now.  Thank you!
