### ISSUE TITLE
laravel/sanctum v3.0 Support

### ISSUE THREAD

**Issue by cesaric** [bolivir/laravel-doctrine-sanctum#65]
Laravel 10 requires **laravel/sanctum:v3.0** to suffice **illuminate/support:v10**.

There's a new "expires_at" column:  https://github.com/laravel/sanctum/blob/3.x/UPGRADE.md

**Comment by bolivir** [comment]
Should now be support by using version https://github.com/bolivir/laravel-doctrine-sanctum/releases/tag/v3.0.0
